/* ================= ایستگاه شکار ماشین‌ها ================= */
const ICO={
 "الاکلنگ":`<path d="M40 48 L30 70 H50Z" fill="#8A5427"/><rect x="6" y="40" width="68" height="7" rx="3" fill="#D08A4B" transform="rotate(-12 40 44)"/><rect x="8" y="30" width="14" height="12" rx="3" fill="#E4553A" transform="rotate(-12 40 44)"/><rect x="58" y="36" width="12" height="8" rx="3" fill="#2F6BD0" transform="rotate(-12 40 44)"/>`,
 "دربازکن نوشابه":`<rect x="14" y="30" width="16" height="38" rx="5" fill="#2F8F4E"/><rect x="17" y="22" width="10" height="10" fill="#2F8F4E"/><rect x="15" y="18" width="14" height="6" rx="2" fill="#C7D3DE"/><path d="M22 20 L66 8" stroke="#8C9BB0" stroke-width="8" stroke-linecap="round"/><circle cx="24" cy="20" r="5" fill="none" stroke="#5E6E86" stroke-width="3"/>`,
 "جارو":`<path d="M52 6 L30 56" stroke="#B8743A" stroke-width="6" stroke-linecap="round"/><path d="M18 56 H44 L50 74 H12Z" fill="#E0B24A"/><path d="M20 62 v10 M28 62 v10 M36 62 v10 M44 62 v10" stroke="#B88A2A" stroke-width="2"/>`,
 "سرسرهٔ پارک":`<path d="M12 72 V22 M24 72 V22" stroke="#5E6E86" stroke-width="4"/><path d="M12 32 H24 M12 44 H24 M12 56 H24" stroke="#5E6E86" stroke-width="3"/><path d="M24 22 Q48 30 56 50 Q62 66 74 70" stroke="#E4553A" stroke-width="8" fill="none" stroke-linecap="round"/>`,
 "رمپ ویلچر":`<path d="M6 70 L60 44 V70Z" fill="#9CB4C8"/><rect x="60" y="30" width="16" height="40" fill="#C7D3DE"/><circle cx="34" cy="48" r="9" fill="none" stroke="#2F6BD0" stroke-width="4"/><path d="M34 38 V30 H42" stroke="#2F6BD0" stroke-width="4" fill="none" stroke-linecap="round"/>`,
 "تختهٔ بار زدن کامیون":`<rect x="40" y="26" width="36" height="30" fill="#4F7FD8"/><circle cx="48" cy="60" r="6" fill="#1B2A41"/><circle cx="68" cy="60" r="6" fill="#1B2A41"/><path d="M4 70 L40 50 V56 L10 70Z" fill="#C98A4B"/><rect x="18" y="46" width="12" height="12" fill="#E0A45F" transform="rotate(-29 24 52)"/>`,
 "چاقو":`<path d="M8 50 L50 26 Q60 22 64 30 L20 56Z" fill="#C3CDD9" stroke="#5E6E86" stroke-width="2"/><rect x="54" y="30" width="22" height="10" rx="4" fill="#8A5427" transform="rotate(-28 60 34)"/>`,
 "تبر":`<path d="M22 70 L50 16" stroke="#B8743A" stroke-width="7" stroke-linecap="round"/><path d="M40 12 Q64 8 70 24 L50 32Z" fill="#8C9BB0" stroke="#5E6E86" stroke-width="2"/>`,
 "نوک میخ":`<rect x="34" y="8" width="12" height="6" rx="2" fill="#5E6E86"/><rect x="37" y="14" width="6" height="44" fill="#8C9BB0"/><path d="M37 58 H43 L40 72Z" fill="#8C9BB0"/><circle cx="40" cy="66" r="11" fill="none" stroke="#C2417A" stroke-width="3"/>`,
 "درِ بطری آب":`<rect x="26" y="30" width="28" height="44" rx="8" fill="#9ED3F0"/><rect x="31" y="20" width="18" height="12" fill="#9ED3F0"/><rect x="28" y="10" width="24" height="12" rx="3" fill="#2F6BD0"/><path d="M29 13 h22 M29 17 h22" stroke="#fff" stroke-width="1.5"/>`,
 "درِ شیشهٔ مربا":`<rect x="18" y="26" width="44" height="46" rx="8" fill="#E4553A" opacity=".85"/><rect x="16" y="14" width="48" height="14" rx="4" fill="#D9A520"/><path d="M18 18 h44 M18 23 h44" stroke="#fff" stroke-width="1.5"/>`,
 "پیچ لولای در":`<rect x="22" y="10" width="36" height="10" rx="4" fill="#8C9BB0"/><rect x="34" y="20" width="12" height="42" fill="#B9C4D2"/><path d="M34 62 H46 L40 74Z" fill="#B9C4D2"/><path d="M31 28 L49 24 M31 36 L49 32 M31 44 L49 40 M31 52 L49 48" stroke="#5E6E86" stroke-width="2.5"/>`,
 "دستگیرهٔ در":`<rect x="10" y="6" width="44" height="70" rx="4" fill="#D59A5C"/><circle cx="46" cy="42" r="9" fill="#FFC43D" stroke="#B88A2A" stroke-width="2"/><rect x="46" y="38" width="26" height="8" rx="4" fill="#FFC43D" stroke="#B88A2A" stroke-width="2"/>`,
 "فرمان ماشین":`<circle cx="40" cy="40" r="28" fill="none" stroke="#1B2A41" stroke-width="7"/><circle cx="40" cy="40" r="8" fill="#1B2A41"/><path d="M40 40 L14 46 M40 40 L66 46 M40 40 V68" stroke="#1B2A41" stroke-width="6"/>`,
 "پیچ‌گوشتی":`<rect x="8" y="30" width="30" height="20" rx="9" fill="#E4553A"/><rect x="38" y="37" width="30" height="6" fill="#8C9BB0"/><path d="M68 37 L76 40 L68 43Z" fill="#8C9BB0"/>`,
 "میلهٔ پرچم مدرسه":`<rect x="22" y="12" width="4" height="62" fill="#8C9BB0"/><circle cx="24" cy="12" r="5" fill="none" stroke="#1B2A41" stroke-width="2.5"/><path d="M26 16 H62 L54 26 L62 36 H26Z" fill="#2F8F4E"/><path d="M30 12 V70" stroke="#7A5634" stroke-width="1.5"/>`,
 "چاه با قرقرهٔ بالای سرش":`<path d="M16 34 L40 12 L64 34" stroke="#E4553A" stroke-width="5" fill="none"/><circle cx="40" cy="26" r="7" fill="none" stroke="#1B2A41" stroke-width="3"/><path d="M34 26 V50 M46 26 V44" stroke="#7A5634" stroke-width="2"/><rect x="18" y="54" width="44" height="20" rx="3" fill="#A3ACB8"/><rect x="28" y="44" width="10" height="10" fill="#8FA3B5"/>`,
 "جرثقیل":`<rect x="14" y="20" width="8" height="54" fill="#FFB020"/><path d="M14 20 H70" stroke="#FFB020" stroke-width="7"/><path d="M60 24 V50" stroke="#7A5634" stroke-width="2"/><circle cx="60" cy="24" r="4" fill="none" stroke="#1B2A41" stroke-width="2"/><rect x="52" y="50" width="16" height="12" fill="#E0A45F"/>`
};

const MCAT=[{n:"اهرم",c:"#D97706"},{n:"سطح شیب‌دار",c:"#0F9488"},{n:"گوه",c:"#C2417A"},{n:"پیچ",c:"#8A5A2B"},{n:"چرخ و محور",c:"#7C4DCC"},{n:"قرقره",c:"#B7791F"},{n:"ماشین مرکب",c:"#3B6FD4"}];
const MICON=[
 `<path d="M3 16 L21 10" stroke="currentColor" stroke-width="2.8" stroke-linecap="round"/><path d="M12 13.5 L8.5 21 H15.5Z" fill="currentColor"/>`,
 `<path d="M3 20 H21 V6Z" fill="currentColor"/>`,`<path d="M6 4 H18 L12 21Z" fill="currentColor"/>`,
 `<rect x="9.5" y="3" width="5" height="15" fill="currentColor"/><path d="M12 22 L9.5 18 H14.5Z" fill="currentColor"/><path d="M7 8 L17 6 M7 12 L17 10 M7 16 L17 14" stroke="currentColor" stroke-width="1.6"/>`,
 `<circle cx="12" cy="12" r="8.5" fill="none" stroke="currentColor" stroke-width="2.4"/><circle cx="12" cy="12" r="2.6" fill="currentColor"/><path d="M12 12 L18 6.5" stroke="currentColor" stroke-width="2.2"/>`,
 `<path d="M12 2 V5.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="10" r="4.5" fill="none" stroke="currentColor" stroke-width="2.4"/><path d="M7.5 10 V21 M16.5 10 V15" stroke="currentColor" stroke-width="2"/><rect x="13.5" y="15" width="6" height="6" rx="1" fill="currentColor"/>`,
 `<circle cx="6.5" cy="16" r="4.5" fill="none" stroke="currentColor" stroke-width="2.2"/><circle cx="17.5" cy="16" r="4.5" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M6.5 16 L11 8 H16 L17.5 16 M11 8 L10 5 H8" stroke="currentColor" stroke-width="2" fill="none" stroke-linejoin="round"/>`];
const ITEMS=[
 ["الاکلنگ",0,1,"یک تخته روی یک تکیه‌گاه؛ ساده‌ترین اهرم."],["دربازکن نوشابه",0,1,"نوک دربازکن روی درِ بطری تکیه می‌کند و دست تو دستهٔ بلندش را بالا می‌کشد."],["جارو",0,2,"دست بالایی تکیه‌گاه است و دست پایینی نیرو وارد می‌کند."],["منگنه",0,2,"لولای عقب منگنه تکیه‌گاه است."],["انبرک",0,2,"دو اهرم که در یک سر به هم وصل شده‌اند."],["پاروی قایق",0,3,"پارو دور جاپاروییِ لبهٔ قایق می‌چرخد و آب را هل می‌دهد."],["فرغون",0,3,"چرخ جلو تکیه‌گاه است و بار بین چرخ و دست تو قرار دارد."],
 ["سرسرهٔ پارک",1,1,"یک سطح کج که بالا و پایین را به هم وصل می‌کند."],["رمپ ویلچر",1,1,"به‌جای پله، یک راه شیب‌دار طولانی‌تر و آسان‌تر."],["تختهٔ بار زدن کامیون",1,2,"جعبه را به‌جای بلند کردن، روی تخته هل می‌دهند."],["جادهٔ پیچ‌درپیچ کوه",1,2,"جاده را مستقیم به قله نمی‌کشند تا شیبش کم باشد."],
 ["چاقو",2,1,"لبهٔ تیزش دو سطح شیب‌دار پشت به پشت است."],["تبر",2,1,"نیروی رو به پایین را به نیروی رو به دو طرف تبدیل می‌کند."],["نوک میخ",2,2,"نوک تیز میخ راه را در چوب باز می‌کند."],["گوهٔ زیر در",2,2,"زیر در فرو می‌رود و آن را نگه می‌دارد."],["دندان‌های جلو",2,3,"دندان‌های پیش لبهٔ تیز دارند و غذا را می‌بُرند."],
 ["درِ بطری آب",3,1,"شیارهای دور گلوی بطری سطح شیب‌داری‌اند که دور آن پیچیده شده."],["درِ شیشهٔ مربا",3,1,"چند دور می‌چرخانی تا محکم بسته شود."],["پیچ لولای در",3,2,"با هر دور چرخیدن، کمی در چوب فرو می‌رود."],["تهِ پیچ‌دارِ لامپ",3,2,"لامپ را می‌چرخانی و شیارهای تهِ آن، لامپ را در سرپیچ فرو می‌برند."],["چهارپایهٔ پیانو که با چرخاندن بالا و پایین می‌رود",3,3,"زیرش یک پیچ بزرگ است."],
 ["دستگیرهٔ در",4,1,"دستگیرهٔ بزرگ را می‌چرخانی و میلهٔ باریک وسط می‌چرخد."],["فرمان ماشین",4,1,"چرخ بزرگ فرمان، میلهٔ وسط را با نیروی کم می‌چرخاند."],["پیچ‌گوشتی",4,2,"دستهٔ پهن چرخ است و تنهٔ باریک محور."],["شیر آب",4,2,"دستهٔ شیر را می‌چرخانی تا میلهٔ داخلش بچرخد."],["چاه با دستهٔ چرخان",4,2,"دسته را می‌چرخانی و محور، طناب سطل را می‌پیچد."],
 ["میلهٔ پرچم مدرسه",5,1,"طناب را پایین می‌کشی و پرچم بالا می‌رود."],["جرثقیل",5,2,"چند قرقره با هم بارهای خیلی سنگین را بلند می‌کنند."],["چاه با قرقرهٔ بالای سرش",5,2,"طناب از روی قرقره رد می‌شود و سطل بالا می‌آید."],["پردهٔ سالن نمایش",5,3,"طناب از روی قرقره‌های بالای صحنه رد می‌شود."],
 ["دوچرخه",6,3,"چرخ و محور (چرخ‌ها و پدال)، اهرم (دستهٔ ترمز) و پیچ؛ چند ماشین ساده با هم."],["ناخن‌گیر",6,3,"دو اهرم با لبه‌های تیز گوه‌ای."],["چرخ‌گوشت دستی",6,3,"دستهٔ چرخان، پیچ داخلی و تیغهٔ گوه‌ای."],["قوطی‌بازکن دستی",6,3,"دسته‌ها اهرم‌اند، دستهٔ چرخان (پروانه) چرخ و محور است و تیغه گوه است."]];
function makeSort(A,item,nb,onPick){const pic=KID()&&ICO[item[0]];const svg=A.svg,P=A.P;A.view(440);const st={cx:320,cy:pic?76:92,drag:false,hover:null,done:null};
  const cols=nb===7?4:3,bw=nb===7?146:196,bh=100,gx=(640-cols*bw)/(cols+1);const bins=MCAT.slice(0,nb).map((c,i)=>{const row=Math.floor(i/cols),inRow=Math.min(cols,nb-row*cols),col=i%cols,g2=(640-inRow*bw)/(inRow+1);return{i,x:g2+col*(bw+g2),y:200+row*(bh+14),c};});
  const binAt=p=>bins.find(b=>p.x>=b.x&&p.x<=b.x+bw&&p.y>=b.y&&p.y<=b.y+bh);
  function card(x,y){if(pic)return `<g><rect x="${x-150}" y="${y-60}" width="300" height="120" rx="18" fill="#fff" stroke="#F0B429" stroke-width="3"/><g transform="translate(${x+20} ${y-50}) scale(1.25)">${pic}</g><text x="${x-12}" y="${y+12}" text-anchor="start" font-size="${item[0].length>12?20:28}" font-family="LalezarLocal,VazirLocal,Tahoma" fill="${INK}" direction="rtl">${item[0]}</text></g>`;return `<g><rect x="${x-150}" y="${y-44}" width="300" height="88" rx="18" fill="#fff" stroke="#F0B429" stroke-width="3"/><rect x="${x-150}" y="${y-44}" width="300" height="10" rx="5" fill="#FFE08A"/><text x="${x}" y="${y+14}" text-anchor="middle" font-size="${item[0].length>18?26:36}" font-family="LalezarLocal,VazirLocal,Tahoma" fill="${INK}" direction="rtl">${item[0]}</text></g>`;}
  function render(){let s=`<defs><linearGradient id="sg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#E6F4EA"/><stop offset="1" stop-color="#F7FCF8"/></linearGradient></defs><rect width="640" height="520" fill="url(#sg)"/>`;
    bins.forEach(b=>{const hv=st.hover===b.i,dn=st.done&&st.done.i===b.i;s+=`<g data-zone="bin" data-c="${b.i}" style="cursor:pointer"><rect x="${b.x}" y="${b.y}" width="${bw}" height="${bh}" rx="16" fill="${dn?(st.done.ok?"#DDF3E6":"#FDE3DC"):hv?"#FFF6D6":"#fff"}" stroke="${dn?(st.done.ok?GRN:RED):hv?"#F0B429":b.c.c}" stroke-width="${hv||dn?4:2.5}"/><path d="M${b.x+10} ${b.y+bh-14} h${bw-20}" stroke="${b.c.c}" stroke-width="3" opacity=".25"/><g transform="translate(${b.x+bw/2-19} ${b.y+10}) scale(1.6)" style="color:${b.c.c}">${MICON[b.i]}</g>${T(b.x+bw/2,b.y+78,b.c.n,{size:nb===7?19:22,col:INK,halo:false})}</g>`;});
    if(!st.drag&&!st.done)s+=`<g data-drag="card" style="cursor:grab">${card(st.cx,st.cy)}</g>`;if(st.done)s+=`<g opacity=".9">${card(320,st.cy)}</g>`;
        P.paint(s);}
  dragKit(svg,{blocked:()=>A.locked,start(d){return d.drag==="card"?{}:null;},begin(g,p){st.drag=true;P.ghost(card(0,0),p.x,p.y);render();},move(g,p){P.move(p.x,p.y);const b=binAt(p);const h=b?b.i:null;if(h!==st.hover){st.hover=h;render();}},
    end(g,p){P.clear();st.drag=false;st.hover=null;const b=binAt(p);render();if(b)onPick(b.i);},tap(){},zoneTap(z){if(z.zone==="bin")onPick(+z.c);}});
  render();return{st,render,mark(i,ok){st.done={i,ok};render();},clear(){st.done=null;render();}};}
const ST_sort={key:"sort",name:"شکار ماشین‌ها",c:"#2F8F4E",sub:"هر وسیله کدام ماشین ساده است؟",
 intro:"کارت هر وسیله را بردار و در جعبهٔ ماشین سادهٔ آن بینداز. در مرحلهٔ آخر ماشین‌های مرکب هم هستند؛ یعنی وسیله‌هایی که از چند ماشین ساده ساخته شده‌اند.",
 art(){let s=`<rect width="640" height="520" fill="#DDF0E2"/>`;for(let i=0;i<6;i++){const x=70+(i%3)*180,y=150+Math.floor(i/3)*130;s+=`<rect x="${x}" y="${y}" width="140" height="104" rx="20" fill="#fff" stroke="${MCAT[i].c}" stroke-width="3"/><g transform="translate(${x+46} ${y+18}) scale(2)" style="color:${MCAT[i].c}">${MICON[i]}</g>`;}s+=`<rect x="200" y="40" width="240" height="80" rx="18" fill="#fff" stroke="#F0B429" stroke-width="3"/>`+T(320,92,"دستگیرهٔ در",{size:26,halo:false});return s;},
 lab(A){A.prompt("آزمایشگاه: هر کارتی را که آمد در جعبهٔ درست بینداز. این‌جا امتیاز ندارد؛ فقط تمرین است.");let k=0;const order=shuffle(rng(Date.now()),ITEMS);
   const show=()=>{const it=order[k%order.length];const so=makeSort(A,it,7,i=>{so.mark(i,i===it[1]);A.fb(i===it[1]?"درست! "+it[3]:`${it[0]} ${MCAT[it[1]].n} است. ${it[3]}`,i===it[1]?"ok":"no");});A.refresh=()=>so.render();};show();A.counter("");A.formula("");
   const c=A.ctrl("");btn(c,"کارت بعدی","go",()=>{k++;A.fb("");show();});},
 kid:[
  {id:"sort.a1",title:"شش ماشین ساده",desc:"کارت هر وسیله را در جعبهٔ درست بینداز.",gen(r){return kidSort(r,0);}},
  {id:"sort.a2",title:"وسیله‌های بیشتر",desc:"وسیله‌های تازه، با همان شش جعبه.",gen(r){return kidSort(r,1);}},
  {id:"sort.a3",title:"همه با هم",desc:"کارت‌های همهٔ وسیله‌ها، درهم.",gen(r){return kidSort(r,2);}}],
 levels:[
  {id:"sort.1",title:"شش ماشین ساده",desc:"وسیله‌های آشنا را در جعبهٔ درست بینداز.",gen(r){return sortPick(r,1,6,false);}},
  {id:"sort.2",title:"وسیله‌های خانه",desc:"وسیله‌های بیشتر از آشپزخانه و انباری.",gen(r){return sortPick(r,2,6,false);}},
  {id:"sort.3",title:"سخت‌تر",desc:"وسیله‌هایی که ماشین ساده‌شان پنهان‌تر است.",gen(r){return sortPick(r,3,6,false,true);}},
  {id:"sort.4",title:"ماشین مرکب",desc:"جعبهٔ هفتم اضافه شد: ماشین‌هایی که از چند ماشین ساده ساخته شده‌اند.",gen(r){return sortPick(r,3,6,true,true);}}],
 endless(r,d){const pool=ITEMS.filter(it=>it[2]<=Math.min(3,Math.floor(d))&&(d>=3.5||it[1]!==6));return{item:pick(r,pool),nb:d>=3.5?7:6};},
 mount(sp,A){A.counter("");A.formula("");A.prompt(KID()?"این کدام ماشین ساده است؟ کارت را در جعبه بینداز.":"این وسیله کدام ماشین ساده است؟<small>کارت را بردار و در جعبهٔ درست بینداز، یا روی جعبهٔ درست بزن.</small>");const it=sp.item;A.hint(`M320 ${KID()?76:92} L${sp.nb===7?90:118} 250`);
   const so=makeSort(A,it,sp.nb,i=>{if(A.locked)return;const ok=i===it[1];so.mark(i,ok);const res=A.judge(ok,{ok:it[3],retry:"یک بار دیگر: به کاری که وسیله انجام می‌دهد فکر کن. می‌چرخد؟ می‌شکافد؟ روی تکیه‌گاه بالا و پایین می‌رود؟",final:`${it[0]} ${MCAT[it[1]].n} است. ${it[3]}`});
     if(!ok&&!A.locked)later(900,()=>so.clear());if(!ok&&A.locked)later(600,()=>so.mark(it[1],true));});A.refresh=()=>so.render();A.ctrl("");}};
function sortPick(r,dmax,n,withC,hardFirst){let pool=ITEMS.filter(it=>it[2]<=dmax&&(withC||it[1]!==6));if(hardFirst)pool=pool.filter(it=>it[2]>=2);
  let pick6=[];const byCat={};pool.forEach(it=>(byCat[it[1]]=byCat[it[1]]||[]).push(it));const cats=shuffle(r,Object.keys(byCat));
  if(withC){pick6=shuffle(r,byCat[6]).slice(0,2);cats.filter(c=>c!=="6").slice(0,n-2).forEach(c=>pick6.push(pick(r,byCat[c])));}else cats.slice(0,n).forEach(c=>pick6.push(pick(r,byCat[c])));
  while(pick6.length<n)pick6.push(pick(r,pool));return shuffle(r,pick6).map(item=>({item,nb:withC?7:6}));}

function kidSort(r,set){const G1=["الاکلنگ","سرسرهٔ پارک","چاقو","درِ بطری آب","دستگیرهٔ در","میلهٔ پرچم مدرسه"],G2=["جارو","رمپ ویلچر","تبر","پیچ لولای در","فرمان ماشین","چاه با قرقرهٔ بالای سرش"],G3=["دربازکن نوشابه","تختهٔ بار زدن کامیون","نوک میخ","درِ شیشهٔ مربا","پیچ‌گوشتی","جرثقیل"];
  const names=set===0?G1:set===1?G2:shuffle(r,G1.concat(G2,G3)).slice(0,6);const pool=set===2?names:shuffle(r,names);return pool.map(n=>({item:ITEMS.find(it=>it[0]===n),nb:6}));}
