/* ================= ایستگاه گوه و پیچ ================= */
/* برچسب گزینه‌ها؛ برای پایهٔ دوم و سوم بدون عدد */
const rankWord=(k,o,ws)=>{const w=ws[Math.min(o.length,5)]||ws[3];return w[o.slice().sort((a,b)=>a-b).indexOf(k)];};
function wedgeLbl(k,o){return KID()?"گوهٔ "+rankWord(k,o,{2:["کوتاه","بلند"],3:["کوتاه","متوسط","بلند"],4:["خیلی کوتاه","کوتاه","بلند","خیلی بلند"],5:["خیلی کوتاه","کوتاه","متوسط","بلند","خیلی بلند"]}):fa(k)+" سانتی‌متر";}
function screwLbl(k,o){return KID()?"شیار "+rankWord(k,o,{2:["ریز","درشت"],3:["ریز","متوسط","درشت"],4:["خیلی ریز","ریز","درشت","خیلی درشت"]}):"گام "+fa(k)+" میلی‌متر ("+fa(12/k)+" دور)";}
function wedgeIcon(L){return `<path d="M13 3 H27 L20 ${Math.min(27,4+L*2)}Z" fill="#C3CDD9" stroke="#5E6E86" stroke-width="1.6" stroke-linejoin="round"/>`;}
function screwIcon(p){let s=`<rect x="16" y="3" width="8" height="21" fill="#B9C4D2"/><path d="M16 24 H24 L20 27Z" fill="#B9C4D2"/>`;const sp=p*2.2+1;for(let y=22;y>4;y-=sp)s+=`<path d="M13 ${y+1.5} L27 ${y-2}" stroke="#5E6E86" stroke-width="1.8"/>`;return s;}
function makeWedge(A,cfg){const svg=A.svg,P=A.P;A.view(404);const G=380,T0=250,CX=320;const st={L:cfg.L,R:cfg.R,S:cfg.S,dep:0,split:0,busy:false,flash:0,edit:cfg.edit!==false,hideF:!!cfg.hideF,done:false};
  const F=()=>st.R*2/st.L,Lp=()=>st.L*9,need=()=>Lp()*.85;
  function render(){const ok=canLift(F(),st.S),q=st.split,tip=T0-10+st.dep,top=tip-Lp();let s=bgOut(G);
    s+=`<path d="M${CX-13} ${top} H${CX+13} L${CX} ${tip}Z" fill="#C3CDD9" stroke="#5E6E86" stroke-width="2.5" stroke-linejoin="round"/><path d="M${CX-6} ${top+5} L${CX} ${tip-10}" stroke="#fff" stroke-width="2.5" opacity=".7"/>`;
    const half=sd=>{const ex=CX+sd*72,sw=sd>0?1:0;return `<g transform="translate(${sd*18*q} 0) rotate(${sd*10*q} ${ex} ${G})"><path d="M${CX} ${T0} H${ex} V${G} H${CX}Z" fill="#A8703A"/><path d="M${CX+sd*22} ${T0+14} V${G-10} M${CX+sd*50} ${T0+12} V${G-14}" stroke="#8A5427" stroke-width="3" stroke-linecap="round"/><path d="M${CX} ${T0-14} A72 14 0 0 ${sw} ${ex} ${T0} A72 14 0 0 ${sw} ${CX} ${T0+14}Z" fill="#EDC08A"/><path d="M${CX} ${T0-8} A42 8 0 0 ${sw} ${CX+sd*42} ${T0} A42 8 0 0 ${sw} ${CX} ${T0+8}" fill="none" stroke="#C98A4B" stroke-width="2"/></g>`;};
    s+=half(-1)+half(1)+(q===0?`<path d="M${CX} ${T0-14} V${T0+14}" stroke="#8A5427" stroke-width="1.5" opacity=".6"/>`:"");
    if(S.forces&&!st.done){const fl=Math.max(24,Math.min(110,F()*1.5));s+=arrow(CX-56,top-4-fl,CX-56,top+6,11,st.hideF?"#7D8CA3":ok?GRN:RED)+T(CX-76,top+8-fl/2,`نیروی لازم<tspan class="num">: ${st.hideF?"؟":fa(r1(F()))}</tspan>`,{size:13,col:st.hideF?INK:ok?GRN:RED,anchor:"start"});}
    if(st.edit&&!st.done)s+=`<g data-drag="wedge" style="cursor:ns-resize"><rect x="${CX-40}" y="${top-30}" width="80" height="${Lp()+30}" fill="#fff" fill-opacity="0"/><rect x="${CX-32}" y="${top-24}" width="64" height="24" rx="10" fill="${st.flash?RED:"#FFC43D"}" stroke="#fff" stroke-width="3"/>${T(CX,top-6,"⇩",{size:18,col:INK,halo:false})}</g>`;
    if(!q)s+=`<line x1="${CX+100}" y1="${T0-10}" x2="${CX+100}" y2="${T0-10+need()}" stroke="${MUT}" stroke-width="2" stroke-dasharray="4 4"/>`+T(CX+108,T0+need()/2,NUMS()?`باید ${fa(st.L)} سانتی‌متر فرو برود`:"باید تا اینجا فرو برود",{size:12,col:MUT,anchor:"end"});
    s+=gBar(st.hideF?0:F(),st.S,20,36,200);
    P.paint(s);
    A.counter(`<span class="cc">طول گوه: <b>${fa(st.L)} سانتی‌متر</b></span><span class="cc">پهنای گوه: <b>۲ سانتی‌متر</b></span><span class="cc">نیروی مقاوم چوب: <b class="num">${fa(st.R)} نیوتن</b></span><span class="cc ${ok?"":"r"}">نیروی لازم: <b class="num">${st.hideF?"؟":fa(r1(F()))+" نیوتن"}</b></span>`);
    A.formula(FX(`${sy("F","1")} = ${sy("F","2")} × ${sy("w")} ÷ ${sy("L")}`,st.hideF?"":`${sy("F","1")} = ${fa(st.R)} × ۲ ÷ ${fa(st.L)} = ${fa(r1(F()))} N`,[[sy("F","1"),"نیروی لازم (N)"],[sy("F","2"),"نیروی مقاوم چوب (N)"],[sy("w"),"پهنای پشت گوه (cm)"],[sy("L"),"طول گوه (cm)"]]));}
  let y0=0,d0=0;
  dragKit(svg,{blocked:()=>A.locked||st.busy||!st.edit||st.done,start(d,p){if(d.drag!=="wedge")return null;y0=p.y;d0=st.dep;return{};},begin(){},
    move(g,p){const dy=p.y-y0;if(!canLift(F(),st.S)){st.dep=clamp(d0+dy,0,6);st.flash=1;if(cfg.onBlocked)cfg.onBlocked();render();return;}st.dep=clamp(d0+dy,0,need());render();
      if(st.dep>=need()-1e-6&&!st.done){st.done=true;st.busy=true;tween(700,pp=>{st.split=ease(pp);render();},()=>{st.busy=false;cfg.onDone&&cfg.onDone();});}},
    end(){st.flash=0;if(!st.done&&!canLift(F(),st.S))st.dep=0;render();},tap(){}});
  render();return{st,render,F,auto(done){st.busy=true;tween(1300,p=>{st.dep=need()*ease(p);render();},()=>{st.done=true;tween(600,p=>{st.split=ease(p);render();},()=>{st.busy=false;done&&done();});});}};}
function makeScrew(A,cfg){const svg=A.svg,P=A.P;A.view(404);const G=380,CX=320,HY=150,D=12,MM=5;const st={p:cfg.p,R:cfg.R,S:cfg.S,ang:0,busy:false,flash:0,edit:cfg.edit!==false,hideF:!!cfg.hideF,done:false};
  const F=()=>st.R*st.p/12,turns=()=>st.ang/(2*Math.PI),depth=()=>Math.min(D,turns()*st.p);
  function render(){const ok=canLift(F(),st.S),y0=226+depth()*MM,len=84,sp=st.p*MM;let s=bgOut(G);
    let th="";const ph=turns()%1;for(let y=y0+len-12-ph*sp;y>y0+3;y-=sp)th+=`<path d="M${CX-11} ${y+sp*.22} L${CX+11} ${y-sp*.22}" stroke="#5E6E86" stroke-width="3" stroke-linecap="round"/>`;
    s+=`<rect x="${CX-8}" y="${y0}" width="16" height="${len-12}" fill="#B9C4D2"/><path d="M${CX-8} ${y0+len-12} H${CX+8} L${CX} ${y0+len}Z" fill="#B9C4D2"/>${th}<rect x="${CX-24}" y="${y0-12}" width="48" height="13" rx="5" fill="#8C9BB0"/>`;
    s+=`<rect x="${CX-3.5}" y="${y0-50}" width="7" height="38" fill="#7D8CA3"/>`;
    let stripes="";for(let i=0;i<4;i++){const x=CX-14+(((i/4)+ph)%1)*28;stripes+=`<line x1="${x}" y1="${y0-96}" x2="${x}" y2="${y0-58}" stroke="#D9483A" stroke-width="3.5" stroke-linecap="round"/>`;}
    s+=`<rect x="${CX-18}" y="${y0-102}" width="36" height="52" rx="12" fill="#FF6F59"/>${stripes}`;
    s+=`<g opacity=".82"><rect x="170" y="290" width="300" height="${G-290}" fill="#D59A5C"/><rect x="170" y="290" width="300" height="6" fill="#EAB47C"/><path d="M186 316 Q260 308 330 318 T460 312 M180 346 Q270 338 350 350 T464 342" stroke="#B97A3F" stroke-width="2.5" fill="none"/></g>`;
    const hx=CX,hy=y0-76,rr=62;if(st.edit&&!st.done){const a=st.ang-Math.PI/2,kx=hx+Math.cos(a)*rr,ky=hy+Math.sin(a)*rr*.45;s+=`<ellipse cx="${hx}" cy="${hy}" rx="${rr}" ry="${rr*.45}" fill="none" stroke="#C2417A" stroke-width="2.5" stroke-dasharray="6 6"/><g data-drag="turn" style="cursor:grab"><circle cx="${kx}" cy="${ky}" r="32" fill="#fff" fill-opacity="0"/><circle cx="${kx}" cy="${ky}" r="19" fill="${st.flash?RED:"#FFC43D"}" stroke="#fff" stroke-width="3"/></g>`;}
    s+=`<rect x="520" y="300" width="100" height="40" rx="20" fill="#fff" stroke="#D4E1E9" stroke-width="2"/>`+T(570,326,`دور: ${fa(Math.floor(turns()+1e-6))}`,{size:15,halo:false});
    s+=gBar(st.hideF?0:F(),st.S,20,36,200);
    P.paint(s);
    A.counter(`<span class="cc">گام پیچ: <b>${fa(st.p)} میلی‌متر</b></span><span class="cc">نیروی مقاوم چوب: <b class="num">${fa(st.R*10)} نیوتن</b></span><span class="cc">دور: <b>${fa(r1(turns()))}</b></span><span class="cc">فرو رفته: <b>${fa(r1(depth()))} میلی‌متر</b></span><span class="cc ${ok?"":"r"}">نیروی لازم: <b class="num">${st.hideF?"؟":fa(r1(F()))+" نیوتن"}</b></span>`);
    A.formula(FX(`${sy("N")} = ${sy("h")} ÷ ${sy("p")}`,`${sy("N")} = ${fa(D)} ÷ ${fa(st.p)} = ${fa(r1(D/st.p))}`,[[sy("N"),"تعداد دور"],[sy("h"),"عمق فرو رفتن (mm)"],[sy("p"),"گام پیچ: فاصلهٔ دو شیار (mm)"]])+(NUMS()?FX(`${sy("F","1")} = ${sy("F","2")} × ${sy("p")} ÷ ${sy("C")}`,st.hideF?"":`${sy("F","1")} = ${fa(st.R*10)} × ${fa(st.p)} ÷ ۱۲۰ = ${fa(r1(F()))} N`,[[sy("F","1"),"نیروی دست (N)"],[sy("F","2"),"نیروی مقاوم چوب (N)"],[sy("C"),"راه دست در یک دور: ۱۲۰ mm"]]):""));}
  let last=0;
  dragKit(svg,{blocked:()=>A.locked||st.busy||!st.edit||st.done,start(d,p){if(d.drag!=="turn")return null;const hy=226+depth()*MM-76;last=Math.atan2((p.y-hy)/.45,p.x-CX);return{hy};},begin(){},
    move(g,p){const hy=g.hy;const a=Math.atan2((p.y-hy)/.45,p.x-CX);let da=a-last;if(da>Math.PI)da-=2*Math.PI;if(da<-Math.PI)da+=2*Math.PI;last=a;
      if(!canLift(F(),st.S)){st.flash=1;if(cfg.onBlocked)cfg.onBlocked();render();return;}const maxA=D/st.p*2*Math.PI;st.ang=clamp(st.ang+da,0,maxA);render();if(st.ang>=maxA-1e-6&&!st.done){st.done=true;render();cfg.onDone&&cfg.onDone();}},
    end(){st.flash=0;render();},tap(){}});
  render();return{st,render,F,auto(done){const maxA=D/st.p*2*Math.PI;st.busy=true;tween(1800,p=>{st.ang=maxA*ease(p);render();},()=>{st.busy=false;st.done=true;render();done&&done();});}};}
const WEDGE_MCQ={1:["گوه یعنی لبهٔ تیزی که چیزها را از هم باز می‌کند. کدام‌یک گوه است؟",["تبر","فرمان ماشین","قرقره"],0,"لبهٔ تیز تبر دو سطح شیب‌دار پشت به پشت است؛ یعنی گوه."],
 2:["پیچ در واقع کدام ماشین ساده است که دور یک میله پیچیده شده؟",["اهرم","سطح شیب‌دار","قرقره"],1,"اگر یک مثلث کاغذی را دور مداد بپیچی، لبهٔ آن شکل شیار پیچ می‌شود؛ پیچ یک سطح شیب‌دار است که دور میله پیچیده شده."],
 3:["کدام گوه راحت‌تر در چوب فرو می‌رود؟",["گوهٔ کوتاه و پهن","گوهٔ دراز و باریک","فرقی ندارند"],1,"گوهٔ دراز و باریک نیروی کمتری می‌خواهد، ولی باید بیشتر فرو برود."],
 4:["پیچی با شیارهای ریزتر (نزدیک‌تر به هم)...",["نیروی بیشتر و دور کمتر می‌خواهد","نیروی کمتر و دور بیشتر می‌خواهد","هیچ فرقی ندارد"],1,"شیار ریزتر مثل سطح شیب‌دار کم‌شیب‌تر است: نیروی کمتر، ولی دور بیشتر."]};
const ST_wedge={key:"wedge",name:"گوه و پیچ",c:"#C2417A",sub:"شکافتن چوب و پیچاندن پیچ",
 intro:"گوه را پایین بکش تا کنده را بشکافد و پیچ را بچرخان تا در چوب برود. گوه و پیچ هر دو سطح شیب‌دارند: نیروی کمتر، راه بیشتر.",
 art(){let h=bgOut(380).replace(/id="go"/,'id="ae"').replace(/url\(#go\)/,"url(#ae)");h+=`<path d="M307 150 H333 L320 262Z" fill="#C3CDD9" stroke="#5E6E86" stroke-width="2.5"/><path d="M320 250 H392 V380 H320Z M320 250 H248 V380 H320Z" fill="#A8703A"/><ellipse cx="320" cy="250" rx="72" ry="14" fill="#EDC08A"/>`+arrow(320,70,320,140,11,GRN);return h;},
 lab(A){let mode="w";const go=()=>{if(mode==="w"){A.prompt("آزمایشگاه گوه: یک گوه انتخاب کن و آن را پایین بکش.");let L=4,wd;const mk=()=>{wd=makeWedge(A,{L,R:60,S:35,onDone:()=>A.fb("کنده شکافت!","ok"),onBlocked:()=>A.fb("نیرویت کافی نیست؛ گوهٔ درازتری انتخاب کن.","no")});A.refresh=()=>wd.render();};mk();
     const c=A.ctrl("");c.insertAdjacentHTML("beforeend",`<div class="ctrl" id="ws">${[2,3,4,6,8].map(k=>`<button class="opt ${k===L?"sel":""}" data-l="${k}" type="button"><svg viewBox="0 0 40 28" aria-hidden="true">${wedgeIcon(k)}</svg>${wedgeLbl(k,[2,3,4,6,8])}</button>`).join("")}</div>`);
     c.querySelector("#ws").onclick=e=>{const b=e.target.closest("[data-l]");if(!b)return;L=+b.dataset.l;c.querySelectorAll("#ws .opt").forEach(x=>x.classList.toggle("sel",x===b));A.fb("");mk();};btn(c,"از اول","",()=>{mk();A.fb("");});btn(c,"آزمایش پیچ","pri",()=>{mode="s";A.fb("");go();});}
   else{A.prompt("آزمایشگاه پیچ: پیچی با گام دلخواه انتخاب کن و بچرخان. تعداد دورها را بشمار.");let p=3,sc;const mk=()=>{sc=makeScrew(A,{p,R:90,S:30,onDone:()=>A.fb(`پیچ کامل رفت؛ ${fa(12/p)} دور چرخاندی.`,"ok"),onBlocked:()=>A.fb("پیچ خیلی سفت است؛ پیچی با گام کوچک‌تر (شیار ریزتر) انتخاب کن.","no")});A.refresh=()=>sc.render();};mk();
     const c=A.ctrl("");c.insertAdjacentHTML("beforeend",`<div class="ctrl" id="ss">${[6,4,3,2].map(k=>`<button class="opt ${k===p?"sel":""}" data-p="${k}" type="button"><svg viewBox="0 0 40 28" aria-hidden="true">${screwIcon(k)}</svg>${screwLbl(k,[6,4,3,2])}</button>`).join("")}</div>`);
     c.querySelector("#ss").onclick=e=>{const b=e.target.closest("[data-p]");if(!b)return;p=+b.dataset.p;c.querySelectorAll("#ss .opt").forEach(x=>x.classList.toggle("sel",x===b));A.fb("");mk();};btn(c,"از اول","",()=>{mk();A.fb("");});btn(c,"آزمایش گوه","pri",()=>{mode="w";A.fb("");go();});}};go();},
 kid:[
  {id:"wedge.a1",title:"گوهٔ تیز",desc:"گوه‌ای انتخاب کن که چوب را بشکافد.",gen(){return[{t:"wc",R:50,S:30,opts:[2,4,6]},{t:"mcq",q:1},{t:"wc",R:80,S:30,opts:[2,4,6,8]},{t:"mcq",q:3}];}},
  {id:"wedge.a2",title:"پیچاندن پیچ",desc:"پیچ را بچرخان تا در چوب برود.",gen(){return[{t:"sc",R:60,S:25,opts:[6,4,2]},{t:"sc",R:90,S:25,opts:[6,3,2]},{t:"mcq",q:4},{t:"wc",R:100,S:30,opts:[2,4,8]}];}}],
 levels:[
  {id:"wedge.1",title:"گوه و پیچ",desc:"گوه یا پیچی را انتخاب کن که نیرویت کافی باشد، و بشناس کدام وسیله گوه است.",gen(){return[{t:"wc",R:50,S:30,opts:[2,3,4,6]},{t:"mcq",q:1},{t:"sc",R:60,S:25,opts:[6,4,3,2]},{t:"mcq",q:3},{t:"wc",R:80,S:30,opts:[2,3,4,6]},{t:"mcq",q:2}];}},
  {id:"wedge.2",title:"شمردن دورها",desc:"گام کوچک‌تر یعنی دور بیشتر. تعداد دورها را حساب کن.",gen(){return[{t:"sc",R:90,S:25,opts:[6,4,3,2]},{t:"turns",p:3},{t:"wc",R:100,S:30,opts:[2,3,4,6,8]},{t:"turns",p:2},{t:"sc",R:120,S:25,opts:[6,4,3,2]},{t:"mcq",q:4}];}},
  {id:"wedge.3",title:"فرمول گوه و پیچ",desc:"نیروی لازم برای گوه و پیچ را حساب کن.",gen(){const b=S.track==="b";return[{t:"wF",R:90,L:6},{t:"sc",R:150,S:30,opts:[6,4,3,2]},b?{t:"turns",p:6}:{t:"sF",R:120,p:3},{t:"wc",R:120,S:35,opts:[2,3,4,6,8]},{t:"turns",p:4},{t:"wF",R:100,L:8}];}},
  {id:"wedge.4",title:"قهرمان گوه و پیچ",desc:"نیروی مقاوم بیشتر و نیروی تو کمتر.",gen(r){return[{t:"wc",R:150,S:40,opts:[2,3,4,6,8]},{t:"sF",R:180,p:2},{t:"sc",R:180,S:40,opts:[6,4,3,2]},{t:"mcq",q:pick(r,[2,4])},{t:"wF",R:130,L:4},{t:"sc",R:200,S:35,opts:[6,4,3,2]}];}}],
 endless(r,d){const tp=pick(r,d<2?["wc","sc","mcq"]:S.track==="b"?["wc","sc","turns","wF"]:["wc","sc","turns","wF","sF"]);if(tp==="mcq")return{t:"mcq",q:ri(r,1,4)};if(tp==="turns")return{t:"turns",p:pick(r,[2,3,4,6])};
   if(tp==="wF"){const L=pick(r,[2,4,5,8]);return{t:"wF",R:L*ri(r,2,8)*5/2,L};}if(tp==="sF"){const p=pick(r,[2,3,4,6]);return{t:"sF",R:ri(r,3,12)*12/p*p,p};}
   for(let k=0;k<60;k++){const R=ri(r,4,16)*10,Sv=ri(r,4,9)*5;if(tp==="wc"){const o=[2,3,4,6,8],b=o.find(L=>canLift(R*2/L,Sv));if(b&&b>2&&!o.some(L=>R*2/L===Sv))return{t:"wc",R,S:Sv,opts:o};}else{const o=[6,4,3,2],b=o.find(p=>canLift(R*p/12,Sv));if(b&&b<6&&!o.some(p=>R*p/12===Sv))return{t:"sc",R,S:Sv,opts:o};}}return{t:"wc",R:60,S:30,opts:[2,3,4,6]};},
 mount(sp,A){
  if(sp.t==="mcq"){const wd=makeWedge(A,{L:4,R:60,S:60,edit:false});A.refresh=()=>wd.render();const Q=WEDGE_MCQ[sp.q];A.prompt(Q[0]);const c=A.ctrl("");const m=mcq(c,Q[1],(i,b)=>{if(A.locked)return;if(i===Q[2]){m.disable();m.mark(i,"right");A.judge(true,{ok:Q[3]});}else{m.mark(i,"wrong");b.disabled=true;A.judge(false,{retry:"به شکل وسیله فکر کن: تیز است؟ شیار دارد؟",final:Q[3]});if(A.locked){m.disable();m.mark(Q[2],"right");}}});return;}
  if(sp.t==="wc"||sp.t==="sc"){const isW=sp.t==="wc",o=sp.opts,best=isW?o.find(L=>canLift(sp.R*2/L,sp.S)):o.find(p=>canLift(sp.R*p/12,sp.S));
    if(isW){const top=240-o[0]*9;A.hint(`M320 ${top-12} L320 ${top+70}`);}else A.hint("M320 122 A62 28 0 1 1 319.9 122");
    A.prompt(KID()?(isW?"گوه‌ای انتخاب کن و آن را پایین بکش تا چوب بشکافد. هر چند بار خواستی امتحان کن.":"پیچی انتخاب کن و بچرخان تا در چوب برود. هر چند بار خواستی امتحان کن."):isW?`کنده را بشکاف. نیروی مقاوم چوب ${fa(sp.R)} نیوتن و نیروی تو <b>${fa(sp.S)} نیوتن</b> است. هر چند بار خواستی امتحان کن.<small>کوتاه‌ترین گوه‌ای را انتخاب کن که نیرویت کافی باشد، بعد آن را پایین بکش.</small>`:`پیچ را در تخته فرو کن. نیروی تو <b>${fa(sp.S)} نیوتن</b> است. هر چند بار خواستی امتحان کن.<small>پیچی انتخاب کن که نیرویت کافی باشد و کمترین دور را بخواهد، بعد بچرخان.</small>`);
    let v=o[0],obj,bl=false;const mk=()=>{const common={R:sp.R,S:sp.S,onBlocked:()=>{if(!bl){bl=true;A.trial(false,{k:{retry:isW?"گوه فرو نمی‌رود. گوهٔ تیزتری انتخاب کن.":"پیچ نمی‌چرخد. پیچی با شیارهای ریزتر انتخاب کن.",final:isW?"گوهٔ تیزتر و درازتری لازم بود.":"پیچی با شیارهای ریزتر لازم بود."},retry:isW?"گوه فرو نمی‌رود؛ گوهٔ درازتری انتخاب کن.":"پیچ نمی‌چرخد؛ پیچی با شیار ریزتر انتخاب کن.",final:isW?`گوهٔ ${fa(best)} سانتی‌متری لازم بود: ${fa(sp.R)} × ۲ ÷ ${fa(best)} = ${fa(r1(sp.R*2/best))} نیوتن.`:`پیچ با گام ${fa(best)} میلی‌متر لازم بود: نیروی ${fa(r1(sp.R*best/12))} نیوتن.`});}},
      onDone:()=>{const b=KID()||v===best;(b?A.trial:A.judge)(true,{k:{ok:isW?"چوب شکافت!":"پیچ رفت!"},ok:b?(isW?"کنده شکافت، با کمترین فرو بردن.":`پیچ رفت، با کمترین تعداد دور (${fa(12/v)} دور).`):(isW?`شکافت، ولی گوهٔ ${fa(best)} سانتی‌متری هم کافی بود و کمتر فرو می‌رفت.`:`پیچ رفت، ولی پیچ با گام ${fa(best)} میلی‌متر هم کافی بود و دور کمتری می‌خواست.`),pts:b?undefined:1});}};
      obj=isW?makeWedge(A,Object.assign({L:v},common)):makeScrew(A,Object.assign({p:v},common));A.refresh=()=>obj.render();};mk();
    const c=A.ctrl("");c.insertAdjacentHTML("beforeend",`<div class="ctrl" id="vs">${o.map(k=>`<button class="opt ${k===v?"sel":""}" data-v="${k}" type="button"><svg viewBox="0 0 40 28" aria-hidden="true">${isW?wedgeIcon(k):screwIcon(k)}</svg>${isW?wedgeLbl(k,o):screwLbl(k,o)}</button>`).join("")}</div>`);
    c.querySelector("#vs").onclick=e=>{if(A.locked)return;const b=e.target.closest("[data-v]");if(!b)return;v=+b.dataset.v;bl=false;c.querySelectorAll("#vs .opt").forEach(x=>x.classList.toggle("sel",x===b));mk();};return;}
  let obj,q,ans,unit,steps,expl,retry;
  if(sp.t==="turns"){obj=makeScrew(A,{p:sp.p,R:60,S:100,edit:false});q=`پیچ باید ۱۲ میلی‌متر در چوب فرو برود و گامش ${fa(sp.p)} میلی‌متر است. چند دور باید بچرخانی؟ (تعداد دور = عمق ÷ گام)`;ans=12/sp.p;unit="دور";steps=[1];expl=`۱۲ ÷ ${fa(sp.p)} = ${fa(ans)} دور.`;retry="عمق را بر گام پیچ تقسیم کن.";}
  else if(sp.t==="wF"){obj=makeWedge(A,{L:sp.L,R:sp.R,S:100,edit:false,hideF:true});q=`نیروی مقاوم چوب ${fa(sp.R)} نیوتن، پهنای پشت گوه ۲ سانتی‌متر و طولش ${fa(sp.L)} سانتی‌متر است. نیروی لازم چقدر است؟ (نیرو × طول گوه = نیروی مقاوم × پهنای پشت گوه)`;ans=sp.R*2/sp.L;unit="نیوتن";steps=[1,10];expl=`${fa(sp.R)} × ۲ ÷ ${fa(sp.L)} = ${fa(r1(ans))} نیوتن.`;retry="نیروی مقاوم را در پهنا ضرب کن و بر طول گوه تقسیم کن.";}
  else{obj=makeScrew(A,{p:sp.p,R:sp.R,S:100,edit:false,hideF:true});q=`نیروی مقاوم چوب ${fa(sp.R*10)} نیوتن و گام پیچ ${fa(sp.p)} میلی‌متر است. دست تو در هر دور ۱۲۰ میلی‌متر راه می‌رود. نیروی لازم چقدر است؟ (نیرو × راه دست در یک دور = نیروی مقاوم × گام)`;ans=sp.R*sp.p/12;unit="نیوتن";steps=[1,10];expl=`${fa(sp.R*10)} × ${fa(sp.p)} ÷ ۱۲۰ = ${fa(r1(ans))} نیوتن.`;retry="نیروی مقاوم را در گام ضرب کن و بر راه دست (۱۲۰) تقسیم کن.";}
  A.refresh=()=>obj.render();A.prompt(q);const c=A.ctrl("");const stp=stepper(c,{init:0,max:300,steps,unit});
  const chk=btn(c,"بررسی","go",()=>{const ok=Math.abs(stp.get()-ans)<.051;A.judge(ok,{ok:expl,retry,final:expl});if(A.locked){chk.disabled=true;stp.disable();obj.st.hideF=false;obj.render();obj.auto();}});
 }};
