"""Export existing approved lever3 props; no network assets are needed at runtime."""
import base64
import importlib.util
import io
import json
import os
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'design/nanobanana'
old_cwd = Path.cwd()
try:
    os.chdir(ART)
    spec = importlib.util.spec_from_file_location('lever_harm', ART / 'harm.py')
    harm = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(harm)
    assets = {}
    for name, sheet, index, holes in [('plank', 'sheet2', 0, True),
                                      ('stone', 'sheet2', 3, False),
                                      ('wedge', 'sheet_fix', 11, True)]:
        c, a = harm.cut(sheet, [index], holes=holes)
        rgb, alpha = harm.gentle(c, a, (30, 87, 106))
        im = Image.fromarray(np.dstack([rgb, alpha]))
        im = im.crop(im.getbbox())
        # Keep the contact point independent from the rectangular image bounds.
        extra = {}
        if name == 'wedge':
            mask = np.asarray(im)[..., 3]
            row = np.where(mask.max(axis=1) > 128)[0][0] + 2
            cols = np.where(mask[row] > 128)[0]
            extra = {'apexX': float(cols.mean()) / im.width, 'apexY': float(row) / im.height}
        buf = io.BytesIO()
        im.save(buf, format='WEBP', quality=90, method=6)
        assets[name] = {'w': im.width, 'h': im.height,
                        'src': 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode(), **extra}
finally:
    os.chdir(old_cwd)

out = ROOT / 'src/simple-machines/lever_art.js'
out.write_text('/* Generated by tools/build_lever_art.py from approved lever3 props. */\nconst LEVER_ART=' +
               json.dumps(assets, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'{out.relative_to(ROOT)}: {out.stat().st_size} bytes')
