"""Export the approved bal2 mockup's independent balance layers.

Run with Pillow, NumPy, OpenCV, SciPy and scikit-learn installed.
Assets stay embedded, so the standalone/offline game needs no image requests.
"""
import base64
import importlib.util
import json
import os
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'design/nanobanana'
old_cwd = Path.cwd()
try:
    os.chdir(ART)
    spec = importlib.util.spec_from_file_location('balance_harm', ART / 'harm.py')
    harm = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(harm)
    c, a = harm.cut('sheet1', [11, 14, 15])
    o, a2 = harm.gentle(c, a, (242, 198, 109))
finally:
    os.chdir(old_cwd)

# The masks/recolouring follow design/mockups/bal2.py, in source-sheet coordinates.
big = cv2.dilate(a2, np.ones((3, 3), np.uint8))
o[(big > 0) & (a2 < 128)] = harm.INK
a2 = np.maximum(a2, big)
x0, y0 = 283, 442
h, w = a2.shape
yy, xx = np.mgrid[0:h, 0:w]
sx, sy = xx + x0, yy + y0
o = cv2.bilateralFilter(o, 7, 30, 7)
lab = cv2.cvtColor(o, cv2.COLOR_RGB2LAB).astype(float)
hsv = cv2.cvtColor(o, cv2.COLOR_RGB2HSV).astype(float)
lum = lab[..., 0] * 100 / 255
wood = (hsv[..., 1] > 70) & (lum > 22) & (a2 > 0)
light = lab.copy()
light[..., 0] = np.where(wood, np.clip(82 + .32 * (lum - 55), 0, 100) * 255 / 100, lab[..., 0])
light[..., 1] = np.where(wood, 128 + (lab[..., 1] - 128) * .55, lab[..., 1])
light[..., 2] = np.where(wood, 128 + (lab[..., 2] - 128) * .75, lab[..., 2])
o = cv2.cvtColor(np.clip(light, 0, 255).astype(np.uint8), cv2.COLOR_LAB2RGB)
op = (a2 > 0) & ~((c.min(axis=2) > 228) & (sy >= 560) & (sy <= 660) & (sx >= 640) & (sx <= 840))
needle = np.zeros((h, w), np.uint8)
cv2.fillPoly(needle, [np.array([(737, 500), (709, 560), (737, 790), (767, 560)]) - [x0, y0]], 1)
needle = cv2.dilate(needle, np.ones((5, 5), np.uint8)).astype(bool) & op
arcbox = (sx >= 648) & (sx <= 827) & (sy >= 583) & (sy <= 650)
beam = (sy >= 516) & (sy <= 606) & op & ~needle & ~arcbox & ~((sx >= 712) & (sx <= 763) & (sy < 520))
pan1 = (sy > 890) & (sy < 1008) & (sx < 648) & op
pan2 = (sy > 890) & (sy < 1008) & (sx > 827) & op
post = op & ~needle & ~arcbox & ~beam & ~((sy > 606) & (sy < 1008) & ((sx < 648) | (sx > 827)))
# Remove the dark base blotch, as in the approved mockup.
lx = cv2.cvtColor(o, cv2.COLOR_RGB2LAB)[..., 0].astype(float) * 100 / 255
base = (sy > 1030) & op
patch = base & cv2.morphologyEx((lx < 45).astype(np.uint8), cv2.MORPH_OPEN, np.ones((15, 15), np.uint8)).astype(bool) & (sx > 800)
good = base & ~patch & (lx > 55)
if good.any():
    o[patch] = np.median(o[good], 0).astype(np.uint8)
edge = base & ~cv2.erode(op.astype(np.uint8), np.ones((7, 7), np.uint8)).astype(bool)
o[edge & patch] = harm.INK
# Reconstruct wood hidden by the original fixed needle.
hidden = needle & (sy >= 528) & (sy <= 589)
ys, xs = np.where(hidden)
o[ys, xs] = o[ys, np.full_like(xs, 700 - x0)]
a2[ys, xs] = a2[ys, np.full_like(xs, 700 - x0)]
beam |= hidden & (a2 > 0)
post_rgba = np.dstack([o.copy(), np.where(post, a2, 0).astype(np.uint8)])
col = (sx >= 713) & (sx <= 762) & (sy >= 478) & (sy <= 800)
ys, xs = np.where(col)
post_rgba[ys, xs] = post_rgba[np.full_like(ys, 805 - y0), xs]

assets = {}
for name, rgba in [('post', post_rgba), ('beam', np.dstack([o, np.where(beam, a2, 0)])),
                   ('panL', np.dstack([o, np.where(pan1, a2, 0)])), ('panR', np.dstack([o, np.where(pan2, a2, 0)]))]:
    im = Image.fromarray(rgba.astype(np.uint8))
    box = im.getbbox()
    crop = im.crop(box)
    # The display scale is ~0.62; 2x assets preserve detail without shipping the sheet.
    import io
    buf = io.BytesIO()
    crop.save(buf, format='WEBP', quality=90, method=6)
    assets[name] = dict(x=box[0] + x0, y=box[1] + y0, w=crop.width, h=crop.height,
                       src='data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode())
out = ROOT / 'src/simple-machines/balance_art.js'
out.write_text('/* Generated by tools/build_balance_art.py from the approved bal2 mockup. */\nconst BAL_ART=' + json.dumps(assets, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'{out.relative_to(ROOT)}: {out.stat().st_size} bytes')
